                                                                                                                                                                                                                     pg_get_functiondef                                                                                                                                                                                                                     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.finance_sku_order_line_details_core_delegate_20260625(p_start date DEFAULT NULL::date, p_end date DEFAULT NULL::date, p_marketplace text DEFAULT NULL::text, p_account_id uuid DEFAULT NULL::uuid, p_marketplace_sku text DEFAULT NULL::text, p_local_sku text DEFAULT NULL::text, p_search text DEFAULT NULL::text, p_payout_filter text DEFAULT 'all'::text, p_page integer DEFAULT 1, p_page_size integer DEFAULT 25)+
  RETURNS jsonb                                                                                                                                                                                                                                                                                                                                                                                                                                            +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                                         +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                                                                         +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                                                                                                                                                                              +
  SET statement_timeout TO '25s'                                                                                                                                                                                                                                                                                                                                                                                                                           +
 AS $function$\r                                                                                                                                                                                                                                                                                                                                                                                                                                           +
 declare\r                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
   v_marketplace_sku text := nullif(trim(coalesce(p_marketplace_sku,'')), '');\r                                                                                                                                                                                                                                                                                                                                                                           +
   v_local_sku text := nullif(trim(coalesce(p_local_sku,'')), '');\r                                                                                                                                                                                                                                                                                                                                                                                       +
   v_search text := nullif(trim(coalesce(p_search,'')), '');\r                                                                                                                                                                                                                                                                                                                                                                                             +
   v_filter text := lower(trim(coalesce(p_payout_filter,'all')));\r                                                                                                                                                                                                                                                                                                                                                                                        +
   v_page_size integer := least(greatest(coalesce(p_page_size,25),1),25);\r                                                                                                                                                                                                                                                                                                                                                                                +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
   j jsonb;\r                                                                                                                                                                                                                                                                                                                                                                                                                                              +
   rows jsonb := '[]'::jsonb;\r                                                                                                                                                                                                                                                                                                                                                                                                                            +
   total_count integer := 0;\r                                                                                                                                                                                                                                                                                                                                                                                                                             +
 begin\r                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
   if lower(coalesce(v_local_sku,'')) in ('unmapped','-', 'null', 'none', 'tidak mapping', 'belum mapping') then\r                                                                                                                                                                                                                                                                                                                                         +
     v_local_sku := null;\r                                                                                                                                                                                                                                                                                                                                                                                                                                +
   end if;\r                                                                                                                                                                                                                                                                                                                                                                                                                                               +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
   if lower(coalesce(v_marketplace_sku,'')) in ('unmapped','-', 'null', 'none') then\r                                                                                                                                                                                                                                                                                                                                                                     +
     v_marketplace_sku := null;\r                                                                                                                                                                                                                                                                                                                                                                                                                          +
   end if;\r                                                                                                                                                                                                                                                                                                                                                                                                                                               +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
   if v_search is not null then\r                                                                                                                                                                                                                                                                                                                                                                                                                          +
     v_search := regexp_replace(v_search, '(^|\s)unmapped(\s|$)', ' ', 'gi');\r                                                                                                                                                                                                                                                                                                                                                                            +
     v_search := nullif(trim(regexp_replace(v_search, '\s+', ' ', 'g')), '');\r                                                                                                                                                                                                                                                                                                                                                                            +
   end if;\r                                                                                                                                                                                                                                                                                                                                                                                                                                               +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
   /*\r                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
     First attempt: pakai parameter UI, tapi local_sku unmapped sudah dinull-kan.\r                                                                                                                                                                                                                                                                                                                                                                        +
   */\r                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
   j := public.finance_sku_order_details(\r                                                                                                                                                                                                                                                                                                                                                                                                                +
     p_start,\r                                                                                                                                                                                                                                                                                                                                                                                                                                            +
     p_end,\r                                                                                                                                                                                                                                                                                                                                                                                                                                              +
     p_marketplace,\r                                                                                                                                                                                                                                                                                                                                                                                                                                      +
     p_account_id,\r                                                                                                                                                                                                                                                                                                                                                                                                                                       +
     v_marketplace_sku,\r                                                                                                                                                                                                                                                                                                                                                                                                                                  +
     v_local_sku,\r                                                                                                                                                                                                                                                                                                                                                                                                                                        +
     v_search,\r                                                                                                                                                                                                                                                                                                                                                                                                                                           +
     p_payout_filter,\r                                                                                                                                                                                                                                                                                                                                                                                                                                    +
     p_page,\r                                                                                                                                                                                                                                                                                                                                                                                                                                             +
     v_page_size\r                                                                                                                                                                                                                                                                                                                                                                                                                                         +
   );\r                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
   rows := coalesce(j->'rows','[]'::jsonb);\r                                                                                                                                                                                                                                                                                                                                                                                                              +
   total_count := coalesce(nullif(j->>'total_count','')::integer, 0);\r                                                                                                                                                                                                                                                                                                                                                                                    +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
   /*\r                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
     UI sering kirim p_payout_filter='paid', tapi TikTok order detail settlement belum match penuh.\r                                                                                                                                                                                                                                                                                                                                                      +
     Kalau paid kosong, fallback all supaya drawer/detail tidak kosong.\r                                                                                                                                                                                                                                                                                                                                                                                  +
   */\r                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
   if coalesce(jsonb_array_length(rows),0) = 0 and v_filter <> 'all' then\r                                                                                                                                                                                                                                                                                                                                                                                +
     j := public.finance_sku_order_details(\r                                                                                                                                                                                                                                                                                                                                                                                                              +
       p_start,\r                                                                                                                                                                                                                                                                                                                                                                                                                                          +
       p_end,\r                                                                                                                                                                                                                                                                                                                                                                                                                                            +
       p_marketplace,\r                                                                                                                                                                                                                                                                                                                                                                                                                                    +
       p_account_id,\r                                                                                                                                                                                                                                                                                                                                                                                                                                     +
       v_marketplace_sku,\r                                                                                                                                                                                                                                                                                                                                                                                                                                +
       v_local_sku,\r                                                                                                                                                                                                                                                                                                                                                                                                                                      +
       v_search,\r                                                                                                                                                                                                                                                                                                                                                                                                                                         +
       'all',\r                                                                                                                                                                                                                                                                                                                                                                                                                                            +
       p_page,\r                                                                                                                                                                                                                                                                                                                                                                                                                                           +
       v_page_size\r                                                                                                                                                                                                                                                                                                                                                                                                                                       +
     );\r                                                                                                                                                                                                                                                                                                                                                                                                                                                  +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
     rows := coalesce(j->'rows','[]'::jsonb);\r                                                                                                                                                                                                                                                                                                                                                                                                            +
     total_count := coalesce(nullif(j->>'total_count','')::integer, 0);\r                                                                                                                                                                                                                                                                                                                                                                                  +
   end if;\r                                                                                                                                                                                                                                                                                                                                                                                                                                               +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
   /*\r                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
     Kalau masih kosong dan UI mengirim search gabungan seperti:\r                                                                                                                                                                                                                                                                                                                                                                                         +
     "unmapped 173063... Happy About It ..."\r                                                                                                                                                                                                                                                                                                                                                                                                             +
     pakai search saja, tanpa sku/local_sku.\r                                                                                                                                                                                                                                                                                                                                                                                                             +
   */\r                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
   if coalesce(jsonb_array_length(rows),0) = 0 and v_search is not null then\r                                                                                                                                                                                                                                                                                                                                                                             +
     j := public.finance_sku_order_details(\r                                                                                                                                                                                                                                                                                                                                                                                                              +
       p_start,\r                                                                                                                                                                                                                                                                                                                                                                                                                                          +
       p_end,\r                                                                                                                                                                                                                                                                                                                                                                                                                                            +
       p_marketplace,\r                                                                                                                                                                                                                                                                                                                                                                                                                                    +
       p_account_id,\r                                                                                                                                                                                                                                                                                                                                                                                                                                     +
       null,\r                                                                                                                                                                                                                                                                                                                                                                                                                                             +
       null,\r                                                                                                                                                                                                                                                                                                                                                                                                                                             +
       v_search,\r                                                                                                                                                                                                                                                                                                                                                                                                                                         +
       'all',\r                                                                                                                                                                                                                                                                                                                                                                                                                                            +
       p_page,\r                                                                                                                                                                                                                                                                                                                                                                                                                                           +
       v_page_size\r                                                                                                                                                                                                                                                                                                                                                                                                                                       +
     );\r                                                                                                                                                                                                                                                                                                                                                                                                                                                  +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
     rows := coalesce(j->'rows','[]'::jsonb);\r                                                                                                                                                                                                                                                                                                                                                                                                            +
     total_count := coalesce(nullif(j->>'total_count','')::integer, 0);\r                                                                                                                                                                                                                                                                                                                                                                                  +
   end if;\r                                                                                                                                                                                                                                                                                                                                                                                                                                               +
 \r                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
   return jsonb_build_object(\r                                                                                                                                                                                                                                                                                                                                                                                                                            +
     'rows', rows,\r                                                                                                                                                                                                                                                                                                                                                                                                                                       +
     'data', rows,\r                                                                                                                                                                                                                                                                                                                                                                                                                                       +
     'items', rows,\r                                                                                                                                                                                                                                                                                                                                                                                                                                      +
     'page', greatest(coalesce(p_page,1),1),\r                                                                                                                                                                                                                                                                                                                                                                                                             +
     'page_size', v_page_size,\r                                                                                                                                                                                                                                                                                                                                                                                                                           +
     'total', total_count,\r                                                                                                                                                                                                                                                                                                                                                                                                                               +
     'count', total_count,\r                                                                                                                                                                                                                                                                                                                                                                                                                               +
     'total_count', total_count,\r                                                                                                                                                                                                                                                                                                                                                                                                                         +
     'total_pages', greatest(ceil(coalesce(total_count,0)::numeric / v_page_size)::integer, 1),\r                                                                                                                                                                                                                                                                                                                                                          +
     'has_more', greatest(coalesce(p_page,1),1) < greatest(ceil(coalesce(total_count,0)::numeric / v_page_size)::integer, 1),\r                                                                                                                                                                                                                                                                                                                            +
     'source', 'finance_sku_order_line_details_delegate_to_order_details_20260625',\r                                                                                                                                                                                                                                                                                                                                                                      +
     'delegate_source', coalesce(j->>'source',''),\r                                                                                                                                                                                                                                                                                                                                                                                                       +
     'requested_payout_filter', p_payout_filter,\r                                                                                                                                                                                                                                                                                                                                                                                                         +
     'effective_marketplace_sku', v_marketplace_sku,\r                                                                                                                                                                                                                                                                                                                                                                                                     +
     'effective_local_sku', v_local_sku,\r                                                                                                                                                                                                                                                                                                                                                                                                                 +
     'effective_search', v_search\r                                                                                                                                                                                                                                                                                                                                                                                                                        +
   );\r                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
 end;\r                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
 $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                +
 
(1 row)

