                                                                                                           pg_get_functiondef                                                                                                           
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.marketplace_submit_return_item_review(p_tenant_id uuid, p_marketplace_order_item_id uuid, p_package_match_status text, p_item_condition text, p_can_restock boolean, p_note text DEFAULT NULL::text)+
  RETURNS jsonb                                                                                                                                                                                                                        +
  LANGUAGE plpgsql                                                                                                                                                                                                                     +
  SECURITY DEFINER                                                                                                                                                                                                                     +
  SET search_path TO 'public'                                                                                                                                                                                                          +
 AS $function$\r                                                                                                                                                                                                                       +
 declare\r                                                                                                                                                                                                                             +
   v_order record;\r                                                                                                                                                                                                                   +
   v_item record;\r                                                                                                                                                                                                                    +
   v_review_status text := 'rejected_no_stock_in';\r                                                                                                                                                                                   +
   v_stock_in_status text := 'not_applicable';\r                                                                                                                                                                                       +
   v_stock_in_count integer := 0;\r                                                                                                                                                                                                    +
   v_qty integer := 0;\r                                                                                                                                                                                                               +
   v_note text;\r                                                                                                                                                                                                                      +
   v_existing_done boolean := false;\r                                                                                                                                                                                                 +
   v_is_stocked_out boolean := false;\r                                                                                                                                                                                                +
 begin\r                                                                                                                                                                                                                               +
   perform public.marketplace_assert_tenant_access(p_tenant_id);\r                                                                                                                                                                     +
 \r                                                                                                                                                                                                                                    +
   select i.* into v_item\r                                                                                                                                                                                                            +
   from public.marketplace_order_items as i\r                                                                                                                                                                                          +
   where i.tenant_id = p_tenant_id\r                                                                                                                                                                                                   +
     and i.marketplace_order_item_id = p_marketplace_order_item_id\r                                                                                                                                                                   +
   for update;\r                                                                                                                                                                                                                       +
 \r                                                                                                                                                                                                                                    +
   if not found then\r                                                                                                                                                                                                                 +
     raise exception 'Item order marketplace tidak ditemukan.';\r                                                                                                                                                                      +
   end if;\r                                                                                                                                                                                                                           +
 \r                                                                                                                                                                                                                                    +
   select o.* into v_order\r                                                                                                                                                                                                           +
   from public.marketplace_orders as o\r                                                                                                                                                                                               +
   where o.tenant_id = p_tenant_id\r                                                                                                                                                                                                   +
     and o.marketplace_order_id = v_item.marketplace_order_id\r                                                                                                                                                                        +
   for update;\r                                                                                                                                                                                                                       +
 \r                                                                                                                                                                                                                                    +
   if not found then\r                                                                                                                                                                                                                 +
     raise exception 'Order marketplace tidak ditemukan.';\r                                                                                                                                                                           +
   end if;\r                                                                                                                                                                                                                           +
 \r                                                                                                                                                                                                                                    +
   select public.marketplace_order_item_is_stocked_out(p_tenant_id, p_marketplace_order_item_id)\r                                                                                                                                     +
     into v_is_stocked_out;\r                                                                                                                                                                                                          +
 \r                                                                                                                                                                                                                                    +
   -- Kalau status order packable/AWAITING_COLLECTION dan bukti fisik stock out ada, rapikan status itemnya dulu.\r                                                                                                                    +
   if v_is_stocked_out and coalesce(v_item.stock_action_status, '') <> 'stock_out_done' then\r                                                                                                                                         +
     update public.marketplace_order_items i\r                                                                                                                                                                                         +
        set stock_action_status = 'stock_out_done',\r                                                                                                                                                                                  +
            reserved_qty = 0,\r                                                                                                                                                                                                        +
            stock_out_at = coalesce(i.stock_out_at, now()),\r                                                                                                                                                                          +
            last_error = null,\r                                                                                                                                                                                                       +
            updated_at = now()\r                                                                                                                                                                                                       +
      where i.marketplace_order_item_id = p_marketplace_order_item_id;\r                                                                                                                                                               +
 \r                                                                                                                                                                                                                                    +
     select i.* into v_item\r                                                                                                                                                                                                          +
     from public.marketplace_order_items as i\r                                                                                                                                                                                        +
     where i.tenant_id = p_tenant_id\r                                                                                                                                                                                                 +
       and i.marketplace_order_item_id = p_marketplace_order_item_id\r                                                                                                                                                                 +
     for update;\r                                                                                                                                                                                                                     +
   end if;\r                                                                                                                                                                                                                           +
 \r                                                                                                                                                                                                                                    +
   select exists (\r                                                                                                                                                                                                                   +
     select 1 from public.marketplace_order_stock_movements m\r                                                                                                                                                                        +
     where m.tenant_id = p_tenant_id\r                                                                                                                                                                                                 +
       and m.marketplace_order_item_id = p_marketplace_order_item_id\r                                                                                                                                                                 +
       and m.action_type in ('marketplace_return_stock_in','marketplace_cancel_stock_in','marketplace_refund_stock_in')\r                                                                                                              +
       and m.movement_status = 'done'\r                                                                                                                                                                                                +
   ) into v_existing_done;\r                                                                                                                                                                                                           +
 \r                                                                                                                                                                                                                                    +
   if coalesce(p_can_restock, false)\r                                                                                                                                                                                                 +
      and lower(coalesce(p_package_match_status, '')) = 'sesuai'\r                                                                                                                                                                     +
      and lower(coalesce(p_item_condition, '')) = 'baik'\r                                                                                                                                                                             +
      and v_is_stocked_out\r                                                                                                                                                                                                           +
   then\r                                                                                                                                                                                                                              +
     v_review_status := 'approved_stock_in';\r                                                                                                                                                                                         +
 \r                                                                                                                                                                                                                                    +
     if v_existing_done or coalesce(v_item.return_review_status, '') = 'stock_in_done' then\r                                                                                                                                          +
       v_stock_in_status := 'skipped_duplicate';\r                                                                                                                                                                                     +
       v_stock_in_count := 0;\r                                                                                                                                                                                                        +
     else\r                                                                                                                                                                                                                            +
       v_qty := greatest(coalesce(v_item.quantity, 0), 0)::integer;\r                                                                                                                                                                  +
       if v_qty <= 0 then\r                                                                                                                                                                                                            +
         raise exception 'Qty return tidak valid.';\r                                                                                                                                                                                  +
       end if;\r                                                                                                                                                                                                                       +
 \r                                                                                                                                                                                                                                    +
       begin\r                                                                                                                                                                                                                         +
         v_note := concat(\r                                                                                                                                                                                                           +
           'Marketplace return stock in ',\r                                                                                                                                                                                           +
           coalesce(v_order.marketplace, '-'),\r                                                                                                                                                                                       +
           ' #', coalesce(v_order.external_order_id, v_order.order_sn, v_order.marketplace_order_id::text),\r                                                                                                                          +
           ' item ', coalesce(v_item.mapped_local_sku, v_item.seller_sku, v_item.marketplace_sku_id, '-')\r                                                                                                                            +
         );\r                                                                                                                                                                                                                          +
 \r                                                                                                                                                                                                                                    +
         perform public.register_stock_transaction(\r                                                                                                                                                                                  +
           v_item.mapped_product_id,\r                                                                                                                                                                                                 +
           'IN',\r                                                                                                                                                                                                                     +
           v_qty,\r                                                                                                                                                                                                                    +
           'marketplace_return_restore',\r                                                                                                                                                                                             +
           v_note,\r                                                                                                                                                                                                                   +
           null,\r                                                                                                                                                                                                                     +
           null\r                                                                                                                                                                                                                      +
         );\r                                                                                                                                                                                                                          +
 \r                                                                                                                                                                                                                                    +
         insert into public.marketplace_order_stock_movements (\r                                                                                                                                                                      +
           marketplace_order_id,\r                                                                                                                                                                                                     +
           marketplace_order_item_id,\r                                                                                                                                                                                                +
           tenant_id,\r                                                                                                                                                                                                                +
           marketplace_account_id,\r                                                                                                                                                                                                   +
           product_id,\r                                                                                                                                                                                                               +
           local_sku,\r                                                                                                                                                                                                                +
           quantity,\r                                                                                                                                                                                                                 +
           action_type,\r                                                                                                                                                                                                              +
           movement_status,\r                                                                                                                                                                                                          +
           created_by\r                                                                                                                                                                                                                +
         ) values (\r                                                                                                                                                                                                                  +
           v_item.marketplace_order_id,\r                                                                                                                                                                                              +
           v_item.marketplace_order_item_id,\r                                                                                                                                                                                         +
           v_item.tenant_id,\r                                                                                                                                                                                                         +
           v_item.marketplace_account_id,\r                                                                                                                                                                                            +
           v_item.mapped_product_id,\r                                                                                                                                                                                                 +
           v_item.mapped_local_sku,\r                                                                                                                                                                                                  +
           v_qty,\r                                                                                                                                                                                                                    +
           case public.marketplace_order_status_group(v_order.order_status)\r                                                                                                                                                          +
             when 'cancelled' then 'marketplace_cancel_stock_in'\r                                                                                                                                                                     +
             when 'return_refund' then 'marketplace_refund_stock_in'\r                                                                                                                                                                 +
             else 'marketplace_return_stock_in'\r                                                                                                                                                                                      +
           end,\r                                                                                                                                                                                                                      +
           'done',\r                                                                                                                                                                                                                   +
           auth.uid()\r                                                                                                                                                                                                                +
         );\r                                                                                                                                                                                                                          +
 \r                                                                                                                                                                                                                                    +
         update public.marketplace_order_items as i\r                                                                                                                                                                                  +
            set returned_qty = v_qty,\r                                                                                                                                                                                                +
                return_review_status = 'stock_in_done',\r                                                                                                                                                                              +
                stock_in_restored_at = now(),\r                                                                                                                                                                                        +
                updated_at = now()\r                                                                                                                                                                                                   +
          where i.marketplace_order_item_id = p_marketplace_order_item_id;\r                                                                                                                                                           +
 \r                                                                                                                                                                                                                                    +
         perform public.marketplace_try_queue_stock_sync_for_item(p_tenant_id, p_marketplace_order_item_id, 'marketplace_return_stock_in');\r                                                                                          +
 \r                                                                                                                                                                                                                                    +
         v_stock_in_status := 'done';\r                                                                                                                                                                                                +
         v_stock_in_count := 1;\r                                                                                                                                                                                                      +
       exception when others then\r                                                                                                                                                                                                    +
         v_stock_in_status := 'failed';\r                                                                                                                                                                                              +
 \r                                                                                                                                                                                                                                    +
         insert into public.marketplace_order_stock_movements (\r                                                                                                                                                                      +
           marketplace_order_id,\r                                                                                                                                                                                                     +
           marketplace_order_item_id,\r                                                                                                                                                                                                +
           tenant_id,\r                                                                                                                                                                                                                +
           marketplace_account_id,\r                                                                                                                                                                                                   +
           product_id,\r                                                                                                                                                                                                               +
           local_sku,\r                                                                                                                                                                                                                +
           quantity,\r                                                                                                                                                                                                                 +
           action_type,\r                                                                                                                                                                                                              +
           movement_status,\r                                                                                                                                                                                                          +
           error_message,\r                                                                                                                                                                                                            +
           created_by\r                                                                                                                                                                                                                +
         ) values (\r                                                                                                                                                                                                                  +
           v_item.marketplace_order_id,\r                                                                                                                                                                                              +
           v_item.marketplace_order_item_id,\r                                                                                                                                                                                         +
           v_item.tenant_id,\r                                                                                                                                                                                                         +
           v_item.marketplace_account_id,\r                                                                                                                                                                                            +
           v_item.mapped_product_id,\r                                                                                                                                                                                                 +
           v_item.mapped_local_sku,\r                                                                                                                                                                                                  +
           greatest(coalesce(v_item.quantity, 0), 0),\r                                                                                                                                                                                +
           'marketplace_return_stock_in',\r                                                                                                                                                                                            +
           'failed',\r                                                                                                                                                                                                                 +
           sqlerrm,\r                                                                                                                                                                                                                  +
           auth.uid()\r                                                                                                                                                                                                                +
         );\r                                                                                                                                                                                                                          +
       end;\r                                                                                                                                                                                                                          +
     end if;\r                                                                                                                                                                                                                         +
   elsif not v_is_stocked_out\r                                                                                                                                                                                                        +
         and coalesce(v_item.reserved_qty, 0) > 0\r                                                                                                                                                                                    +
   then\r                                                                                                                                                                                                                              +
     v_review_status := 'released_reservation';\r                                                                                                                                                                                      +
     v_stock_in_status := 'not_applicable';\r                                                                                                                                                                                          +
 \r                                                                                                                                                                                                                                    +
     update public.marketplace_order_items as i\r                                                                                                                                                                                      +
        set reserved_qty = 0,\r                                                                                                                                                                                                        +
            return_review_status = 'reservation_released',\r                                                                                                                                                                           +
            stock_action_status = 'cancelled_released',\r                                                                                                                                                                              +
            updated_at = now()\r                                                                                                                                                                                                       +
      where i.marketplace_order_item_id = p_marketplace_order_item_id;\r                                                                                                                                                               +
 \r                                                                                                                                                                                                                                    +
     perform public.marketplace_try_queue_stock_sync_for_item(p_tenant_id, p_marketplace_order_item_id, 'marketplace_cancel_release_reservation');\r                                                                                   +
   else\r                                                                                                                                                                                                                              +
     v_review_status := 'rejected_no_stock_in';\r                                                                                                                                                                                      +
     v_stock_in_status := 'not_applicable';\r                                                                                                                                                                                          +
 \r                                                                                                                                                                                                                                    +
     update public.marketplace_order_items as i\r                                                                                                                                                                                      +
        set return_review_status = 'not_restocked',\r                                                                                                                                                                                  +
            updated_at = now()\r                                                                                                                                                                                                       +
      where i.marketplace_order_item_id = p_marketplace_order_item_id;\r                                                                                                                                                               +
   end if;\r                                                                                                                                                                                                                           +
 \r                                                                                                                                                                                                                                    +
   insert into public.marketplace_return_item_reviews (\r                                                                                                                                                                              +
     tenant_id,\r                                                                                                                                                                                                                      +
     marketplace_account_id,\r                                                                                                                                                                                                         +
     marketplace_order_id,\r                                                                                                                                                                                                           +
     marketplace_order_item_id,\r                                                                                                                                                                                                      +
     external_order_id,\r                                                                                                                                                                                                              +
     review_type,\r                                                                                                                                                                                                                    +
     package_match_status,\r                                                                                                                                                                                                           +
     item_condition,\r                                                                                                                                                                                                                 +
     can_restock,\r                                                                                                                                                                                                                    +
     review_status,\r                                                                                                                                                                                                                  +
     stock_in_status,\r                                                                                                                                                                                                                +
     stock_in_movement_count,\r                                                                                                                                                                                                        +
     note,\r                                                                                                                                                                                                                           +
     reviewed_by,\r                                                                                                                                                                                                                    +
     reviewed_at,\r                                                                                                                                                                                                                    +
     updated_at\r                                                                                                                                                                                                                      +
   ) values (\r                                                                                                                                                                                                                        +
     p_tenant_id,\r                                                                                                                                                                                                                    +
     v_item.marketplace_account_id,\r                                                                                                                                                                                                  +
     v_item.marketplace_order_id,\r                                                                                                                                                                                                    +
     v_item.marketplace_order_item_id,\r                                                                                                                                                                                               +
     coalesce(v_order.external_order_id, v_order.order_sn),\r                                                                                                                                                                          +
     case public.marketplace_order_status_group(v_order.order_status)\r                                                                                                                                                                +
       when 'cancelled' then 'cancel'\r                                                                                                                                                                                                +
       when 'return_refund' then 'return_refund'\r                                                                                                                                                                                     +
       else 'return_refund'\r                                                                                                                                                                                                          +
     end,\r                                                                                                                                                                                                                            +
     p_package_match_status,\r                                                                                                                                                                                                         +
     p_item_condition,\r                                                                                                                                                                                                               +
     p_can_restock,\r                                                                                                                                                                                                                  +
     v_review_status,\r                                                                                                                                                                                                                +
     v_stock_in_status,\r                                                                                                                                                                                                              +
     v_stock_in_count,\r                                                                                                                                                                                                               +
     p_note,\r                                                                                                                                                                                                                         +
     auth.uid(),\r                                                                                                                                                                                                                     +
     now(),\r                                                                                                                                                                                                                          +
     now()\r                                                                                                                                                                                                                           +
   )\r                                                                                                                                                                                                                                 +
   on conflict (tenant_id, marketplace_order_item_id)\r                                                                                                                                                                                +
   do update set\r                                                                                                                                                                                                                     +
     package_match_status = excluded.package_match_status,\r                                                                                                                                                                           +
     item_condition = excluded.item_condition,\r                                                                                                                                                                                       +
     can_restock = excluded.can_restock,\r                                                                                                                                                                                             +
     review_status = excluded.review_status,\r                                                                                                                                                                                         +
     stock_in_status = excluded.stock_in_status,\r                                                                                                                                                                                     +
     stock_in_movement_count = excluded.stock_in_movement_count,\r                                                                                                                                                                     +
     note = excluded.note,\r                                                                                                                                                                                                           +
     reviewed_by = excluded.reviewed_by,\r                                                                                                                                                                                             +
     reviewed_at = excluded.reviewed_at,\r                                                                                                                                                                                             +
     updated_at = now();\r                                                                                                                                                                                                             +
 \r                                                                                                                                                                                                                                    +
   update public.marketplace_orders o\r                                                                                                                                                                                                +
      set stock_action_status = case\r                                                                                                                                                                                                 +
            when exists (\r                                                                                                                                                                                                            +
              select 1 from public.marketplace_order_items i\r                                                                                                                                                                         +
              where i.marketplace_order_id = o.marketplace_order_id\r                                                                                                                                                                  +
                and i.return_review_status = 'stock_in_done'\r                                                                                                                                                                         +
            ) then 'return_review_done'\r                                                                                                                                                                                              +
            when exists (\r                                                                                                                                                                                                            +
              select 1 from public.marketplace_order_items i\r                                                                                                                                                                         +
              where i.marketplace_order_id = o.marketplace_order_id\r                                                                                                                                                                  +
                and i.return_review_status = 'reservation_released'\r                                                                                                                                                                  +
            ) then 'cancelled_released'\r                                                                                                                                                                                              +
            else 'return_not_restocked'\r                                                                                                                                                                                              +
          end,\r                                                                                                                                                                                                                       +
          stock_in_restored_at = case when v_stock_in_status = 'done' then now() else o.stock_in_restored_at end,\r                                                                                                                    +
          updated_at = now()\r                                                                                                                                                                                                         +
    where o.marketplace_order_id = v_item.marketplace_order_id;\r                                                                                                                                                                      +
 \r                                                                                                                                                                                                                                    +
   return jsonb_build_object(\r                                                                                                                                                                                                        +
     'ok', v_stock_in_status <> 'failed',\r                                                                                                                                                                                            +
     'review_status', v_review_status,\r                                                                                                                                                                                               +
     'stock_in_status', v_stock_in_status,\r                                                                                                                                                                                           +
     'stock_in_movement_count', v_stock_in_count,\r                                                                                                                                                                                    +
     'physically_stocked_out', v_is_stocked_out,\r                                                                                                                                                                                     +
     'message', case\r                                                                                                                                                                                                                 +
       when v_review_status = 'approved_stock_in' and v_stock_in_status = 'done' then 'Review item selesai. Barang OK dan sudah masuk stock.'\r                                                                                        +
       when v_review_status = 'approved_stock_in' and v_stock_in_status = 'skipped_duplicate' then 'Item ini sudah pernah stock in. Tidak diproses ulang.'\r                                                                           +
       when v_review_status = 'released_reservation' then 'Review item selesai. Reservation dilepas, stock fisik tidak berubah.'\r                                                                                                     +
       else 'Review item selesai. Barang tidak masuk stock.'\r                                                                                                                                                                         +
     end\r                                                                                                                                                                                                                             +
   );\r                                                                                                                                                                                                                                +
 end;\r                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                            +
 
(1 row)

