-- Placeholder for remote migration version 20260608173118.
-- This migration already exists in Supabase remote history but the original local file is missing.
-- Do not add SQL here. Kept only so supabase db push can compare migration history safely.
